version: '3.8'
services:
  php:
    build:
      context: ./php
    volumes:
      - ./app:/app:cached
      - ./php/php.conf:/usr/local/etc/php-fpm.d/logging.conf
    expose:
      - 9000
    env_file:
      - .env
  nginx:
    image: nginx:stable-alpine
    ports:
      - 8080:80
    volumes:
      - ./app:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
  mysql:
    image: mysql:8.1
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    volumes:
      - mysql:/var/lib/mysql
    user: mysql
    env_file:
      - .env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    ports:
      - 8081:80
    env_file:
      - .env
    environment:
      UPLOAD_LIMIT: 50M
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 8082:1080
volumes:
  mysql:
    driver: local
