name: push ts-service to ACR
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      COMPOSER_VERSION: '2.5.8'
    steps:
      - name: Checkout GitHub Actions
        uses: actions/checkout@main

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login into Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_REGISTRY_ENDPOINT }}
          username: ${{ secrets.AZ_SP_CLIENT_ID }}
          password: ${{ secrets.AZ_SP_CLIENT_SECRET }}

      - name: prepare composer
        id: composer_config
        uses: baschny/php-composer-action@v1
        with:
          composer_version: ${{ env.COMPOSER_VERSION }}
          command: get_config

      - name: cache composer downloads
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer_config.outputs.composer_cache_dir }}
          key: composer-v${{ steps.composer_config.outputs.composer_major_version }}

      - name: run composer install
        uses: baschny/php-composer-action@v1
        with:
          composer_version: ${{ env.COMPOSER_VERSION }}
          command: install

      - name: docker build
        run: |
          docker build . -f ./php/Dockerfile -t ${{ vars.IMAGE_NAME }}

      - name: docker tag
        run: |
          docker tag ${{ vars.IMAGE_NAME }} ${{ secrets.ACR_REGISTRY_ENDPOINT }}/${{ vars.IMAGE_NAME }}:latest

      - name: docker push
        run: |
          docker push ${{ secrets.ACR_REGISTRY_ENDPOINT }}/${{ vars.IMAGE_NAME }}:latest

