name: Push to Azure Container Registry Touchdown Stars
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Actions
        uses: actions/checkout@main

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login into Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.AZ_SP_CLIENT_ID }}
          password: ${{ secrets.AZ_SP_CLIENT_SECRET }}

      - name: Build and push Docker images to ACR
        run: |
          docker-compose -f docker-compose.yml build
          docker tag ts-service ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/${{ IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/${{ IMAGE_NAME }}:${{ github.sha }}

