name: Push to Azure Container Registry Touchdown Stars
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Actions
        uses: actions/checkout@main

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login into Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_REGISTRY_ENDPOINT }}
          username: ${{ secrets.AZ_SP_CLIENT_ID }}
          password: ${{ secrets.AZ_SP_CLIENT_SECRET }}

      - name: Docker compose
        run: |
          docker-compose -f docker-compose.yml build

      - name: Docker tag
        run: |
          docker tag ${{ vars.IMAGE_NAME }} ${{ secrets.ACR_REGISTRY_ENDPOINT }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}

      - name: Docker push
        run: |
          docker push ${{ secrets.ACR_REGISTRY_ENDPOINT }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}

